In [1]:
import pandas as pd
import matplotlib.pyplot

In [2]:
datos = "documentos_udea_2004_2024.xlsx"
df = pd.read_excel(datos)
df.head(10)

,tipo_documento,numero,fecha_expedicion,entrada_vigencia,medio_publicacion,resuelve,normas_relacionadas
0,ACTAS,0198,2004/12/14,NaN,NaN,NaN,NaN
1,ACTAS,0283,2004/12/09,NaN,NaN,NaN,NaN
2,ACTAS,0282,2004/12/02,NaN,NaN,NaN,NaN
3,ACTAS,0280,2004/11/18,NaN,NaN,NaN,NaN
4,ACTAS,0279,2004/11/11,NaN,NaN,NaN,NaN
5,ACTAS,0197,2004/11/09,NaN,NaN,NaN,NaN
6,ACTAS,0278,2004/11/04,NaN,NaN,NaN,NaN
7,ACTAS,0277,2004/11/02,NaN,NaN,NaN,NaN
8,ACTAS,0276,2004/10/21,NaN,NaN,NaN,NaN
9,ACTAS,0196,2004/10/12,NaN,NaN,NaN,NaN

In [3]:
df.tail(10)

,tipo_documento,numero,fecha_expedicion,entrada_vigencia,medio_publicacion,resuelve,normas_relacionadas
26028,RESOLUCIONES,50939,2024/01/19,NaN,NORMATIVA.UDEA.EDU.CO,FIJAR LOS DERECHOS DE MATRÍCULA Y COMPLEMENTAR...,NaN
26029,RESOLUCIONES,50949,2024/01/19,NaN,NORMATIVA.UDEA.EDU.CO,TRASLADAR LA PLAZA NO 887 DEL DEPARTAMENTO DE ...,NaN
26030,RESOLUCIONES,50941,2024/01/19,NaN,NORMATIVA.UDEA.EDU.CO,ACEPTAR LA RENUNCIA PRESENTADA POR LA SEÑORA N...,NaN
26031,RESOLUCIONES,50940,2024/01/19,NaN,NORMATIVA.UDEA.EDU.CO,ACEPTAR LA RENUNCIA PRESENTADA POR EL SEÑOR HA...,NaN
26032,RESOLUCIONES,50944,2024/01/19,NaN,NORMATIVA.UDEA.EDU.CO,COMISIONAR Y NOMBRAR AL SEÑOR JULIO EDUARDO HO...,NaN
26033,RESOLUCIONES,50948,2024/01/19,2024/01/19,NORMATIVA.UDEA.EDU.CO,ESTABLECER LINEAMIENTOS PARA LA IMPLEMENTACIÓN...,NaN
26034,RESOLUCIONES,50937,2024/01/17,NaN,NORMATIVA.UDEA.EDU.CO,MODIFICAR EL ARTÍCULO 1 DE LA RESOLUCIÓN RECTO...,RESOLUCION RECTORAL 50835 DEL 27 DE NOVIEMBRE ...
26035,RESOLUCIONES,50936,2024/01/17,NaN,NORMATIVA.UDEA.EDU.CO,CONCEDER COMISIÓN DE SERVICIOS A LA SEÑORA NAT...,NaN
26036,RESOLUCIONES,50938,2024/01/17,NaN,NORMATIVA.UDEA.EDU.CO,CONCEDER COMISIÓN DE SERVICIOS AL SEÑOR GABRIE...,NaN
26037,RESOLUCIONES,50934,2024/01/17,NaN,NORMATIVA.UDEA.EDU.CO,PRORROGAR LA COMISÓN ADMINISTRATIVA DE LA SEÑO...,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26038 entries, 0 to 26037
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   tipo_documento       26038 non-null  str
 1   numero               26038 non-null  str
 2   fecha_expedicion     26038 non-null  str
 3   entrada_vigencia     1555 non-null   str
 4   medio_publicacion    21845 non-null  str
 5   resuelve             25065 non-null  str
 6   normas_relacionadas  2315 non-null   str
dtypes: str(7)
memory usage: 1.4 MB

In [5]:
df.isnull().sum()

tipo_documento             0
numero                     0
fecha_expedicion           0
entrada_vigencia       24483
medio_publicacion       4193
resuelve                 973
normas_relacionadas    23723
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(1034)

In [7]:
antes = df['entrada_vigencia'].copy()
df['entrada_vigencia'] =pd.to_datetime(
    df['entrada_vigencia'],
    format='mixed',
    errors='coerce'
)

In [25]:
df.isnull().sum()

tipo_documento             0
numero                     0
fecha_expedicion           0
entrada_vigencia       24485
medio_publicacion       4193
resuelve                 973
normas_relacionadas    23723
dtype: int64

In [26]:
cambiaron = antes.notna() & df['entrada_vigencia'].isna()

In [28]:
df.iloc[cambiaron]

,tipo_documento,numero,fecha_expedicion,entrada_vigencia,medio_publicacion,resuelve,normas_relacionadas
12753,RESOLUCIONES,2950,2015/09/28,NaT,NORMATIVA.UDEA.EDU.CO,AUTORIZAR LA CONVOCATORIA Y FIJAR REQUISITOS D...,NaN
20949,RESOLUCIONES,47233,2020/08/21,NaT,NORMATIVA.UDEA.EDU.CO,ESTABLECEN LOS LINEAMIENTOS PARA LA ENTREGA DE...,NaN

In [29]:
antes[cambiaron]

12753     2015/2016
20949    2020/28/21
Name: entrada_vigencia, dtype: str

In [30]:
df.loc[20949, 'entrada_vigencia'] = pd.to_datetime('2020/08/21')
df.loc[12753, 'entrada_vigencia'] = pd.to_datetime('2015/09/28')

In [31]:
df.loc[[12753,20949]]

,tipo_documento,numero,fecha_expedicion,entrada_vigencia,medio_publicacion,resuelve,normas_relacionadas
12753,RESOLUCIONES,2950,2015/09/28,2015-09-28,NORMATIVA.UDEA.EDU.CO,AUTORIZAR LA CONVOCATORIA Y FIJAR REQUISITOS D...,NaN
20949,RESOLUCIONES,47233,2020/08/21,2020-08-21,NORMATIVA.UDEA.EDU.CO,ESTABLECEN LOS LINEAMIENTOS PARA LA ENTREGA DE...,NaN

In [32]:
antes_expedicion = df['fecha_expedicion'].copy()
df['fecha_expedicion'] = pd.to_datetime(
    df['fecha_expedicion'],
    format='mixed',
    errors='coerce'
)

In [33]:
df.isnull().sum()

tipo_documento             0
numero                     0
fecha_expedicion           2
entrada_vigencia       24483
medio_publicacion       4193
resuelve                 973
normas_relacionadas    23723
dtype: int64

In [34]:
cambiaron_expedicion = antes_expedicion.notna() & df['fecha_expedicion'].isna()

In [35]:
df.iloc[cambiaron_expedicion]

,tipo_documento,numero,fecha_expedicion,entrada_vigencia,medio_publicacion,resuelve,normas_relacionadas
803,ACTAS,624,NaT,NaT,NORMATIVA.UDEA.EDU.CO,NaN,NaN
15610,RESOLUCIONES,9619,NaT,NaT,NaN,CONCEDER DEDICACION EXCLUSIVA A ADRIANA MARIA ...,NaN

In [ ]:
antes_expedicion[cambiaron_expedicion] # la 15610 es 2016/04/07 y la 803 es 2017/02/23

803      201702/23
15610    2016/04/0
Name: fecha_expedicion, dtype: str

In [38]:
df.loc[803, 'fecha_expedicion'] = pd.to_datetime('2017/02/23')
df.loc[15610, 'fecha_expedicion'] = pd.to_datetime('2016/04/07')

In [39]:
df.iloc[[803, 15610]]

,tipo_documento,numero,fecha_expedicion,entrada_vigencia,medio_publicacion,resuelve,normas_relacionadas
803,ACTAS,624,2017-02-23,NaT,NORMATIVA.UDEA.EDU.CO,NaN,NaN
15610,RESOLUCIONES,9619,2016-04-07,NaT,NaN,CONCEDER DEDICACION EXCLUSIVA A ADRIANA MARIA ...,NaN

In [40]:
df.isnull().sum()

tipo_documento             0
numero                     0
fecha_expedicion           0
entrada_vigencia       24483
medio_publicacion       4193
resuelve                 973
normas_relacionadas    23723
dtype: int64